[r ] tests/fwcfg
failed due to timeout while unpacking.
fixed timeout handling in insall_windbg()

ERROR: cdb.exe not found at: C:\Program Files (x86)\Windows
Kits\10\Debuggers\x86\cdb.exe