staging.backports.simplejson: Use all relative imports
Due to the import structure of the staging module, in
order to make importing the simplejson module possible
in systems without python-simplejson installed already,
use only relative imports. This will avoid the error

ImportError: No module named simplejson.scanner

Found by jferlan.

Signed-off-by: Lucas Meneghel Rodrigues <lmr@redhat.com>