netuser_buffer_test: Failed to compile exp.c on rhel9
1.The error is caused by redefining the same macro or including
the same header file multiple times.So commenting out the
following header includes fixed the compilation error:
//#include <net/if.h>

Signed-off-by: Lei Yang <leiayang@redhat.com>