virt-libvirt: Implement stub for all XML devices
Accessing any vm_xml.devices member requiring an undefined
device xml module resulted in an extremely unhelpful error:

AttributeError: "type object 'exceptions.NotImplementedError' has no
attribute 'new_from_element'"

This commit adds a stub-class generating metaclass for undefined
devices.  The generated stub-class provides the minimal required
interface for the higher-level vm_xml.VMXMLDevices class.  Each
stub class will raise one-warning upon first use.  This is to notify
and make clear to all uses of these devices, that the interface
will likely change in the future.

Added unittests to verify functionality of stub-class metaclass.  Also
added plenty of docstrings and docstring updates.

Signed-off-by: Chris Evich <cevich@redhat.com>