virttest.aexpect: Fix old class Spawn definition.
The base class Spawn for ShellSession was defined in old way(class Spawn).
Then we can not use super() for inherited classes:
TypeError: super() argument 1 must be type, not classobj

Signed-off-by: Yu Mingfei <yumingfei@cn.fujitsu.com>