Merge 'qemu.lib' into 'provider'
The following error would occur during runing the test 'cdrom_test'

    ValueError: Missing test entry point

that because the VT framework wrongly loaded the test module from
'qemu.lib' instead of 'qemu.tests'.

To avoid the this and the potential issue, we can merge 'qemu.lib'
into 'provider' as the two directories are used in the same way.

Signed-off-by: Xu Han <xuhan@redhat.com>