virttest.qemu_vm: Catch all exceptions when sending quit to monitor in destroy
When host or guest under heavy load or in a shutdown status from pre case.
VM process may quit during destory() in any steps and will raise very strange
error message like if it is try to kill vm by monitor:
 error: (9, 'Bad file descriptor')

So catch all kinds of exceptions and judge if the process is alive or not.
Log warning message in the log file instead of through errors.

Signed-off-by: Yiqiao Pu <ypu@redhat.com>