virttest.qemu_storage: Do not create the path when it is None.
In create() function, we will try to create the image's Parent
 directory if not available.

It will raise following error, if image's basename is None.
We get following error in migrate.after_extensive_io.

            # Set in test runtime
            images_base_dir_image2_vm1 = ""

Traceback (most recent call last):
  File "/usr/code/autotest/client/shared/test.py", line 841, in _call_test_function
    return func(*args, **dargs)
  File "/usr/code/autotest/client/shared/test.py", line 299, in execute
    postprocess_profiled_run, args, dargs)
  File "/usr/code/autotest/client/shared/test.py", line 216, in _call_run_once
    *args, **dargs)
  File "/usr/code/autotest/client/shared/test.py", line 322, in run_once_profiling
    self.run_once(*args, **dargs)
  File "/usr/code/autotest/client/tests/virt/virt.py", line 123, in run_once
    env_process.preprocess(self, params, env)
  File "/usr/code/autotest/client/shared/error.py", line 138, in new_fn
    return fn(*args, **kwargs)
  File "/usr/code/autotest/client/tests/virt/virttest/env_process.py", line 448, in preprocess
    process(test, params, env, preprocess_image, preprocess_vm)
  File "/usr/code/autotest/client/tests/virt/virttest/env_process.py", line 283, in process
    _call_image_func()
  File "/usr/code/autotest/client/tests/virt/virttest/env_process.py", line 273, in _call_image_func
    image_func(test, image_params, image_name)
  File "/usr/code/autotest/client/tests/virt/virttest/env_process.py", line 51, in preprocess_image
    image.create(params)
  File "/usr/code/autotest/client/shared/error.py", line 138, in new_fn
    return fn(*args, **kwargs)
  File "/usr/code/autotest/client/tests/virt/virttest/qemu_storage.py", line 125, in create
    os.makedirs(image_dirname)
  File "/usr/lib64/python2.6/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 2] No such file or directory: ''

So make sure image's Parent directory is not None before try to create it.

Signed-off-by: Feng Yang <fyang@redhat.com>