virtio_fs_migration_on_error: Migration test with migration-on-error
Covered the following viriofsd options:
  --migration-on-error abort
  --migration-on-error guest-error

Note we usually use memory-backend-file on s390x for the virtio-fs
testing on RHEL, but for the live migration scenario, we have to use
memory-backend-memfd due to RHEL-58831.

Signed-off-by: Zhenchao Liu <zhencliu@redhat.com>