VMDeadKernelCrashError: Replace exception with VMKernelCrashError
Since the exception type in verify_kernel_crash is updated,
the exception called by cases is updated synchronously.

Signed-off-by: zhenyzha <zhenyzha@redhat.com>